pipeline {
    agent any
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr.Jenkins', description: 'Who should I say Hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['one', 'Two', 'Three'], description: 'Enter your choice')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage('Example') {
            steps {
                echo "Hello ${params.PERSON}"
                echo "Biography about: ${params.BIOGRAPHY}"
                echo "Toggle : ${params.TOGGLE}"
                echo "choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
            }
        }
    }
}
